require("core.keymaps")
require("core.remaps")
require("core.autocmds")
require("core.colorscheme")
require("core.clipboard")
require("core.plugins")
require("core.plugin_config")

vim.cmd('syntax on')
vim.cmd('set cursorline')
vim.cmd('set number')
vim.cmd('set guicursor+=i:blinkon100')
vim.cmd('set mouse=a')
vim.cmd('set tabstop=4')
vim.cmd('set shiftwidth=4 smarttab')
vim.cmd('set splitright')
vim.cmd('set splitbelow')
--vim.cmd('set shell=D:\\dev\\programs\\msys64\\usr\\bin\\bash.exe')
vim.cmd('set shell=cmd.exe')
